### ISSUE TITLE
conversion does not work for gropu folders

### ISSUE THREAD

**Issue by ratermir** [PaulLereverend/NextcloudVideo_Converter#17]
In case source file lies in the group folder, application tries open file from regular user's folder, where the file does not exist. 

So the path, where the app searches for the file,  is 
[NC_databasedir]/[user_name]/files/[path_to_the_file] 

but should be 
[NC_databasedir]/__groupfolders/[group_id]/[path_to_the_file] 

Need to count with "hierarchical" folders, when single group folder acts as a parent for anothe set of (also group) "subfolders"

**Comment by pdschandler** [comment]
same thing happens with external folders shared out to others - when logged in as those other people, the command errors out with the wrong path. External storage does work when it's mounted directly to the user though.

**Comment by PaulLereverend** [comment]
Fixed on latest update 😃 Feel free to let me know if something don't work.

**Comment by RomanYankovsky** [comment]
Still doesn't work with group folders :(

**Comment by WNYmathGuy** [comment]
I'm fully updated with Stable and I just had this happen to me. When I moved the folder of video's back out of a group folder the conversion worked great, while it was a subdirectory of a group folder it threw the can't find video error message. At first, I thought it was the non-DOS names I used so I simplified the name and removed whitespaces, but still it threw can't find video errors.

**Comment by AlbiWe** [comment]
The problem ist, that NextcloudVideo_Converter looks for the file in the path of logged in user, e.g. 
`/var/www/cloud/data/user/files/name_of_groupfolder/file.avi `
and not in the group folder path, in this case e.g. 
`/var/www/cloud/data/__groupfolders/2/file.avi`

**Comment by asereq** [comment]
Same here after the upgrade to version 0.1.5. Still not fixed.

**Comment by PaulLereverend** [comment]
Hi, 
Sorry to hear that. 
This app does not support group folders yet. I will look into it

**Comment by AcidCrash1337** [comment]
The error message is coming from this line:
https://github.com/PaulLereverend/NextcloudVideo_Converter/blob/12dd873211c59e6498b69b5f737b73b0976c81dc/lib/Controller/ConversionController.php#L105

...but the core issue is this line:
https://github.com/PaulLereverend/NextcloudVideo_Converter/blob/12dd873211c59e6498b69b5f737b73b0976c81dc/lib/Controller/ConversionController.php#L90

In my opinion that should be replaced with a function call that will get the path to the file.  In the normal case, it can check $datadirectory/$user/files/... but it would also provide a nice place to add support for group folders, and any other case where Nextcloud puts things in a different location (e.g. external storage?).

I am a programmer, and I have known PHP for about a decade, but I am not familiar with the OCP interface and PHP has evolved over the last decade.  Just hacking around a little bit shows me that we can [detect](https://nextcloud-server.netlify.app/classes/ocp-iconfig#method_getAppValue) if groupfolders are enabled with the following code:
`$this->config->getAppValue("groupfolders", "enabled")`

Alternatively, this will also work:
`\OCP\App::isEnabled('groupfolders')`

Following this ability to call arbitrary methods using namespaces, I attempted to call a getAllFolders() method from the groupfolders app with this:
`\OCA\GroupFolders\Folder\FolderManager::getAllFolders()`

I didn't work, but the reason it didn't work was not because it couldn't find the class or that the method didn't exist, it was because that method uses $this and I was calling it from a static location.  The constructor of this object is also public, but it requires a database connection, which I don't see in the VideoConverter plugin.  If we can get a DB connection, we should be able to call the constructor, then call methods like [getFolderByPath($path)](https://github.com/nextcloud/groupfolders/blob/master/lib/Folder/FolderManager.php#L203).

I'm sorry I wasn't able to solve this one, but I hope that my comments and links are helpful in getting support for group folders in the foreseeable future.

**Comment by AcidCrash1337** [comment]
I figured it out and submitted a pull request https://github.com/PaulLereverend/NextcloudVideo_Converter/pull/60

There may be one more line of code to change from my pull request (the call to scanFolder) but I can't test this part on account of using snap to manage the Nextcloud package (ffmpeg is not accessible to the plugin in this type of deployment).

I may eventually look into how difficult it would be to repackage the Nextcloud snap to include ffmpeg.  That is what would be required to make this plugin work with a snap deployment.

**Comment by PaulLereverend** [comment]
Hi !
The group folders now seems to work in my test environment.
The new version is available here : https://github.com/PaulLereverend/NextcloudVideo_Converter/releases/tag/1.0.0
Can you confirm that it is working for you too ?

**Comment by AcidCrash1337** [comment]
I'll leave testing to other people in this thread (and #57).

I'm using a snap installation, which mounts the `bin` directory as read-only.  This means I can never never get the ffmpeg executable in there, so this Nextcloud app is never going to work for me.  In order to get ffmpeg in there, I'd have to repackage the snap (which would be the equillivant of repackaging a .rpm or .deb file... it's possible, but it'd be a pretty unusual thing to do).  I'll probably do that in the future, but not now.

Anyway, I'm just glad I was able to help.

**Comment by PaulLereverend** [comment]
Group folders are supported in the latest update.
